server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8002
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8003
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false

logging:
  level: INFO
  loggers:
    gt.com.api.radiance: DEBUG
  appenders:
    - type: console

applicationName: radiance

swagger:
    resourcePackage: gt.com.api.radiance.resources

mongo:
  type: uriConfig
  uri: mongodb://localhost:27017/radiance

secretKey: superSecret

apiVersion: 1