server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    gt.com.api: DEBUG

applicationName: radiance

swagger:
    resourcePackage: gt.com.api.radiance.resources

mongo:
  type: uriConfig
  uri: mongodb://localhost:27017/radianceDB

secretKey: superSecret

apiVersion: 1